#ifndef _SYSCALL_VAR_H
#define _SYSCALL_VAR_H
#include <stdarg.h>
#include <stdio.h>

#define CASE_SYSCALL(name, ...) \
  case SYS_##name: return __syscall_SYS_##name(__VA_ARGS__); break; 

/* Internal syscall implementation with varargs, handling parsing exact syscall ABI */
static long __syscall_vargs(long n, va_list ap) {
  switch(n) {
		CASE_SYSCALL (read, va_arg(ap, int),va_arg(ap, void*),va_arg(ap, unsigned int));
		CASE_SYSCALL (write, va_arg(ap, int),va_arg(ap, void*),va_arg(ap, unsigned int));
		CASE_SYSCALL (open, va_arg(ap, void*),va_arg(ap, int),va_arg(ap, int));
		CASE_SYSCALL (close, va_arg(ap, int));
		CASE_SYSCALL (stat, va_arg(ap, void*),va_arg(ap, void*));
		CASE_SYSCALL (fstat, va_arg(ap, int),va_arg(ap, void*));
		CASE_SYSCALL (lstat, va_arg(ap, void*),va_arg(ap, void*));
		CASE_SYSCALL (poll, va_arg(ap, void*),va_arg(ap, unsigned long long),va_arg(ap, int));
		CASE_SYSCALL (lseek, va_arg(ap, int),va_arg(ap, long long),va_arg(ap, int));
		CASE_SYSCALL (mmap, va_arg(ap, void*),va_arg(ap, unsigned int),va_arg(ap, int),va_arg(ap, int),va_arg(ap, int),va_arg(ap, long long));
		CASE_SYSCALL (mprotect, va_arg(ap, void*),va_arg(ap, unsigned int),va_arg(ap, int));
		CASE_SYSCALL (munmap, va_arg(ap, void*),va_arg(ap, unsigned int));
		CASE_SYSCALL (brk, va_arg(ap, void*));
		CASE_SYSCALL (rt_sigaction, va_arg(ap, int),va_arg(ap, void*),va_arg(ap, void*),va_arg(ap, unsigned int));
		CASE_SYSCALL (rt_sigprocmask, va_arg(ap, int),va_arg(ap, void*),va_arg(ap, void*),va_arg(ap, unsigned int));
		CASE_SYSCALL (rt_sigreturn, va_arg(ap, long));
		CASE_SYSCALL (ioctl, va_arg(ap, int),va_arg(ap, int),va_arg(ap, void*));
		CASE_SYSCALL (pread64, va_arg(ap, int),va_arg(ap, void*),va_arg(ap, unsigned int),va_arg(ap, long long));
		CASE_SYSCALL (pwrite64, va_arg(ap, int),va_arg(ap, void*),va_arg(ap, unsigned int),va_arg(ap, long long));
		CASE_SYSCALL (readv, va_arg(ap, int),va_arg(ap, void*),va_arg(ap, int));
		CASE_SYSCALL (writev, va_arg(ap, int),va_arg(ap, void*),va_arg(ap, int));
		CASE_SYSCALL (access, va_arg(ap, void*),va_arg(ap, int));
		CASE_SYSCALL (pipe, va_arg(ap, int*));
		CASE_SYSCALL (select, va_arg(ap, int),va_arg(ap, void*),va_arg(ap, void*),va_arg(ap, void*),va_arg(ap, void*));
		CASE_SYSCALL (sched_yield, );
		CASE_SYSCALL (mremap, va_arg(ap, void*),va_arg(ap, unsigned int),va_arg(ap, unsigned int),va_arg(ap, int),va_arg(ap, void*));
		CASE_SYSCALL (msync, va_arg(ap, void*),va_arg(ap, unsigned int),va_arg(ap, int));
		CASE_SYSCALL (madvise, va_arg(ap, void*),va_arg(ap, unsigned int),va_arg(ap, int));
		CASE_SYSCALL (dup, va_arg(ap, int));
		CASE_SYSCALL (dup2, va_arg(ap, int),va_arg(ap, int));
		CASE_SYSCALL (nanosleep, va_arg(ap, void*),va_arg(ap, void*));
		CASE_SYSCALL (setitimer, va_arg(ap, int),va_arg(ap, void*),va_arg(ap, void*));
		CASE_SYSCALL (getpid, );
		CASE_SYSCALL (socket, va_arg(ap, int),va_arg(ap, int),va_arg(ap, int));
		CASE_SYSCALL (connect, va_arg(ap, int),va_arg(ap, void*),va_arg(ap, unsigned int));
		CASE_SYSCALL (accept, va_arg(ap, int),va_arg(ap, void*),va_arg(ap, void*));
		CASE_SYSCALL (sendto, va_arg(ap, int),va_arg(ap, void*),va_arg(ap, unsigned int),va_arg(ap, int),va_arg(ap, void*),va_arg(ap, unsigned int));
		CASE_SYSCALL (recvfrom, va_arg(ap, int),va_arg(ap, void*),va_arg(ap, unsigned int),va_arg(ap, int),va_arg(ap, void*),va_arg(ap, void*));
		CASE_SYSCALL (sendmsg, va_arg(ap, int),va_arg(ap, void*),va_arg(ap, int));
		CASE_SYSCALL (recvmsg, va_arg(ap, int),va_arg(ap, void*),va_arg(ap, int));
		CASE_SYSCALL (shutdown, va_arg(ap, int),va_arg(ap, int));
		CASE_SYSCALL (bind, va_arg(ap, int),va_arg(ap, void*),va_arg(ap, unsigned int));
		CASE_SYSCALL (listen, va_arg(ap, int),va_arg(ap, int));
		CASE_SYSCALL (getsockname, va_arg(ap, int),va_arg(ap, void*),va_arg(ap, void*));
		CASE_SYSCALL (getpeername, va_arg(ap, int),va_arg(ap, void*),va_arg(ap, void*));
		CASE_SYSCALL (socketpair, va_arg(ap, int),va_arg(ap, int),va_arg(ap, int),va_arg(ap, int*));
		CASE_SYSCALL (setsockopt, va_arg(ap, int),va_arg(ap, int),va_arg(ap, int),va_arg(ap, void*),va_arg(ap, unsigned int));
		CASE_SYSCALL (getsockopt, va_arg(ap, int),va_arg(ap, int),va_arg(ap, int),va_arg(ap, void*),va_arg(ap, void*));
		CASE_SYSCALL (fork, );
		CASE_SYSCALL (execve, va_arg(ap, void*),va_arg(ap, void*),va_arg(ap, void*));
		CASE_SYSCALL (exit, va_arg(ap, int));
		CASE_SYSCALL (wait4, va_arg(ap, int),va_arg(ap, int*),va_arg(ap, int),va_arg(ap, void*));
		CASE_SYSCALL (kill, va_arg(ap, int),va_arg(ap, int));
		CASE_SYSCALL (uname, va_arg(ap, void*));
		CASE_SYSCALL (fcntl, va_arg(ap, int),va_arg(ap, int),va_arg(ap, unsigned long));
		CASE_SYSCALL (flock, va_arg(ap, int),va_arg(ap, int));
		CASE_SYSCALL (fsync, va_arg(ap, int));
		CASE_SYSCALL (fdatasync, va_arg(ap, int));
		CASE_SYSCALL (ftruncate, va_arg(ap, int),va_arg(ap, long long));
		CASE_SYSCALL (getcwd, va_arg(ap, void*),va_arg(ap, unsigned int));
		CASE_SYSCALL (chdir, va_arg(ap, void*));
		CASE_SYSCALL (fchdir, va_arg(ap, int));
		CASE_SYSCALL (rename, va_arg(ap, void*),va_arg(ap, void*));
		CASE_SYSCALL (mkdir, va_arg(ap, void*),va_arg(ap, int));
		CASE_SYSCALL (rmdir, va_arg(ap, void*));
		CASE_SYSCALL (link, va_arg(ap, void*),va_arg(ap, void*));
		CASE_SYSCALL (unlink, va_arg(ap, void*));
		CASE_SYSCALL (symlink, va_arg(ap, void*),va_arg(ap, void*));
		CASE_SYSCALL (readlink, va_arg(ap, void*),va_arg(ap, void*),va_arg(ap, unsigned int));
		CASE_SYSCALL (chmod, va_arg(ap, void*),va_arg(ap, int));
		CASE_SYSCALL (fchmod, va_arg(ap, int),va_arg(ap, int));
		CASE_SYSCALL (chown, va_arg(ap, void*),va_arg(ap, int),va_arg(ap, int));
		CASE_SYSCALL (fchown, va_arg(ap, int),va_arg(ap, int),va_arg(ap, int));
		CASE_SYSCALL (umask, va_arg(ap, int));
		CASE_SYSCALL (gettimeofday, va_arg(ap, void*),va_arg(ap, void*));
		CASE_SYSCALL (getrlimit, va_arg(ap, int),va_arg(ap, void*));
		CASE_SYSCALL (getrusage, va_arg(ap, int),va_arg(ap, void*));
		CASE_SYSCALL (sysinfo, va_arg(ap, void*));
		CASE_SYSCALL (getuid, );
		CASE_SYSCALL (getgid, );
		CASE_SYSCALL (setuid, va_arg(ap, int));
		CASE_SYSCALL (setgid, va_arg(ap, int));
		CASE_SYSCALL (geteuid, );
		CASE_SYSCALL (getegid, );
		CASE_SYSCALL (setpgid, va_arg(ap, int),va_arg(ap, int));
		CASE_SYSCALL (getppid, );
		CASE_SYSCALL (setsid, );
		CASE_SYSCALL (setreuid, va_arg(ap, int),va_arg(ap, int));
		CASE_SYSCALL (setregid, va_arg(ap, int),va_arg(ap, int));
		CASE_SYSCALL (getgroups, va_arg(ap, unsigned int),va_arg(ap, void*));
		CASE_SYSCALL (setgroups, va_arg(ap, unsigned int),va_arg(ap, void*));
		CASE_SYSCALL (setresuid, va_arg(ap, int),va_arg(ap, int),va_arg(ap, int));
		CASE_SYSCALL (setresgid, va_arg(ap, int),va_arg(ap, int),va_arg(ap, int));
		CASE_SYSCALL (getpgid, va_arg(ap, int));
		CASE_SYSCALL (getsid, va_arg(ap, int));
		CASE_SYSCALL (rt_sigpending, va_arg(ap, void*),va_arg(ap, unsigned int));
		CASE_SYSCALL (rt_sigsuspend, va_arg(ap, void*),va_arg(ap, unsigned int));
		CASE_SYSCALL (sigaltstack, va_arg(ap, void*),va_arg(ap, void*));
		CASE_SYSCALL (statfs, va_arg(ap, void*),va_arg(ap, void*));
		CASE_SYSCALL (fstatfs, va_arg(ap, int),va_arg(ap, void*));
		CASE_SYSCALL (prctl, va_arg(ap, int),va_arg(ap, unsigned long),va_arg(ap, unsigned long),va_arg(ap, unsigned long),va_arg(ap, unsigned long));
		CASE_SYSCALL (setrlimit, va_arg(ap, int),va_arg(ap, void*));
		CASE_SYSCALL (chroot, va_arg(ap, void*));
		CASE_SYSCALL (gettid, );
		CASE_SYSCALL (tkill, va_arg(ap, int),va_arg(ap, int));
		CASE_SYSCALL (futex, va_arg(ap, int*),va_arg(ap, int),va_arg(ap, int),va_arg(ap, void*),va_arg(ap, int*),va_arg(ap, int));
		CASE_SYSCALL (sched_getaffinity, va_arg(ap, int),va_arg(ap, unsigned int),va_arg(ap, void*));
		CASE_SYSCALL (getdents64, va_arg(ap, int),va_arg(ap, void*),va_arg(ap, int));
		CASE_SYSCALL (set_tid_address, va_arg(ap, int*));
		CASE_SYSCALL (fadvise, va_arg(ap, int),va_arg(ap, long long),va_arg(ap, long long),va_arg(ap, int));
		CASE_SYSCALL (clock_gettime, va_arg(ap, int),va_arg(ap, void*));
		CASE_SYSCALL (clock_getres, va_arg(ap, int),va_arg(ap, void*));
		CASE_SYSCALL (clock_nanosleep, va_arg(ap, int),va_arg(ap, int),va_arg(ap, void*),va_arg(ap, void*));
		CASE_SYSCALL (exit_group, va_arg(ap, int));
		CASE_SYSCALL (epoll_ctl, va_arg(ap, int),va_arg(ap, int),va_arg(ap, int),va_arg(ap, void*));
		CASE_SYSCALL (openat, va_arg(ap, int),va_arg(ap, void*),va_arg(ap, int),va_arg(ap, int));
		CASE_SYSCALL (mkdirat, va_arg(ap, int),va_arg(ap, void*),va_arg(ap, int));
		CASE_SYSCALL (fchownat, va_arg(ap, int),va_arg(ap, void*),va_arg(ap, int),va_arg(ap, int),va_arg(ap, int));
		CASE_SYSCALL (newfstatat, va_arg(ap, int),va_arg(ap, void*),va_arg(ap, void*),va_arg(ap, int));
		CASE_SYSCALL (unlinkat, va_arg(ap, int),va_arg(ap, void*),va_arg(ap, int));
		CASE_SYSCALL (linkat, va_arg(ap, int),va_arg(ap, void*),va_arg(ap, int),va_arg(ap, void*),va_arg(ap, int));
		CASE_SYSCALL (symlinkat, va_arg(ap, void*),va_arg(ap, int),va_arg(ap, void*));
		CASE_SYSCALL (readlinkat, va_arg(ap, int),va_arg(ap, void*),va_arg(ap, void*),va_arg(ap, unsigned int));
		CASE_SYSCALL (fchmodat, va_arg(ap, int),va_arg(ap, void*),va_arg(ap, int),va_arg(ap, int));
		CASE_SYSCALL (faccessat, va_arg(ap, int),va_arg(ap, void*),va_arg(ap, int),va_arg(ap, int));
		CASE_SYSCALL (pselect6, va_arg(ap, int),va_arg(ap, void*),va_arg(ap, void*),va_arg(ap, void*),va_arg(ap, void*),va_arg(ap, void*));
		CASE_SYSCALL (ppoll, va_arg(ap, void*),va_arg(ap, unsigned long long),va_arg(ap, void*),va_arg(ap, void*),va_arg(ap, unsigned int));
		CASE_SYSCALL (utimensat, va_arg(ap, int),va_arg(ap, void*),va_arg(ap, void*),va_arg(ap, int));
		CASE_SYSCALL (epoll_pwait, va_arg(ap, int),va_arg(ap, void*),va_arg(ap, int),va_arg(ap, int),va_arg(ap, void*),va_arg(ap, unsigned int));
		CASE_SYSCALL (eventfd, va_arg(ap, int));
		CASE_SYSCALL (accept4, va_arg(ap, int),va_arg(ap, void*),va_arg(ap, void*),va_arg(ap, int));
		CASE_SYSCALL (eventfd2, va_arg(ap, int),va_arg(ap, int));
		CASE_SYSCALL (epoll_create1, va_arg(ap, int));
		CASE_SYSCALL (dup3, va_arg(ap, int),va_arg(ap, int),va_arg(ap, int));
		CASE_SYSCALL (pipe2, va_arg(ap, int*),va_arg(ap, int));
		CASE_SYSCALL (prlimit64, va_arg(ap, int),va_arg(ap, int),va_arg(ap, void*),va_arg(ap, void*));
		CASE_SYSCALL (renameat2, va_arg(ap, int),va_arg(ap, void*),va_arg(ap, int),va_arg(ap, void*),va_arg(ap, int));
		CASE_SYSCALL (getrandom, va_arg(ap, void*),va_arg(ap, unsigned int),va_arg(ap, int));
		CASE_SYSCALL (statx, va_arg(ap, int),va_arg(ap, void*),va_arg(ap, int),va_arg(ap, unsigned int),va_arg(ap, void*));
		CASE_SYSCALL (faccessat2, va_arg(ap, int),va_arg(ap, void*),va_arg(ap, int),va_arg(ap, int));
    default: {
      printf("Invalid syscall var call -- NR %d\n",  n);
      return -ENOSYS;
    }
  }
}

/* Internal syscall implementation for non-const syscall NR invocation 
	pre-converted to `long` types */
static long __syscall_var(long n, long a1, long a2, long a3, long a4, long a5, long a6) {
  switch(n) {
		CASE_SYSCALL (read, (int)a1,(void*)a2,(unsigned int)a3);
		CASE_SYSCALL (write, (int)a1,(void*)a2,(unsigned int)a3);
		CASE_SYSCALL (open, (char*)a1,(int)a2,(int)a3);
		CASE_SYSCALL (close, (int)a1);
		CASE_SYSCALL (stat, (char*)a1,(void*)a2);
		CASE_SYSCALL (fstat, (int)a1,(void*)a2);
		CASE_SYSCALL (lstat, (char*)a1,(void*)a2);
		CASE_SYSCALL (poll, (void*)a1,(unsigned long long)a2,(int)a3);
		CASE_SYSCALL (lseek, (int)a1,(long long)a2,(int)a3);
		CASE_SYSCALL (mmap, (void*)a1,(unsigned int)a2,(int)a3,(int)a4,(int)a5,(long long)a6);
		CASE_SYSCALL (mprotect, (void*)a1,(unsigned int)a2,(int)a3);
		CASE_SYSCALL (munmap, (void*)a1,(unsigned int)a2);
		CASE_SYSCALL (brk, (void*)a1);
		CASE_SYSCALL (rt_sigaction, (int)a1,(void*)a2,(void*)a3,(unsigned int)a4);
		CASE_SYSCALL (rt_sigprocmask, (int)a1,(void*)a2,(void*)a3,(unsigned int)a4);
		CASE_SYSCALL (rt_sigreturn, (long)a1);
		CASE_SYSCALL (ioctl, (int)a1,(int)a2,(char*)a3);
		CASE_SYSCALL (pread64, (int)a1,(char*)a2,(unsigned int)a3,(long long)a4);
		CASE_SYSCALL (pwrite64, (int)a1,(char*)a2,(unsigned int)a3,(long long)a4);
		CASE_SYSCALL (readv, (int)a1,(void*)a2,(int)a3);
		CASE_SYSCALL (writev, (int)a1,(void*)a2,(int)a3);
		CASE_SYSCALL (access, (char*)a1,(int)a2);
		CASE_SYSCALL (pipe, (int*)a1);
		CASE_SYSCALL (select, (int)a1,(void*)a2,(void*)a3,(void*)a4,(void*)a5);
		CASE_SYSCALL (sched_yield, );
		CASE_SYSCALL (mremap, (void*)a1,(unsigned int)a2,(unsigned int)a3,(int)a4,(void*)a5);
		CASE_SYSCALL (msync, (void*)a1,(unsigned int)a2,(int)a3);
		CASE_SYSCALL (madvise, (void*)a1,(unsigned int)a2,(int)a3);
		CASE_SYSCALL (dup, (int)a1);
		CASE_SYSCALL (dup2, (int)a1,(int)a2);
		CASE_SYSCALL (nanosleep, (void*)a1,(void*)a2);
		CASE_SYSCALL (setitimer, (int)a1,(void*)a2,(void*)a3);
		CASE_SYSCALL (getpid, );
		CASE_SYSCALL (socket, (int)a1,(int)a2,(int)a3);
		CASE_SYSCALL (connect, (int)a1,(void*)a2,(unsigned int)a3);
		CASE_SYSCALL (accept, (int)a1,(void*)a2,(void*)a3);
		CASE_SYSCALL (sendto, (int)a1,(void*)a2,(unsigned int)a3,(int)a4,(void*)a5,(unsigned int)a6);
		CASE_SYSCALL (recvfrom, (int)a1,(void*)a2,(unsigned int)a3,(int)a4,(void*)a5,(void*)a6);
		CASE_SYSCALL (sendmsg, (int)a1,(void*)a2,(int)a3);
		CASE_SYSCALL (recvmsg, (int)a1,(void*)a2,(int)a3);
		CASE_SYSCALL (shutdown, (int)a1,(int)a2);
		CASE_SYSCALL (bind, (int)a1,(void*)a2,(unsigned int)a3);
		CASE_SYSCALL (listen, (int)a1,(int)a2);
		CASE_SYSCALL (getsockname, (int)a1,(void*)a2,(void*)a3);
		CASE_SYSCALL (getpeername, (int)a1,(void*)a2,(void*)a3);
		CASE_SYSCALL (socketpair, (int)a1,(int)a2,(int)a3,(int*)a4);
		CASE_SYSCALL (setsockopt, (int)a1,(int)a2,(int)a3,(void*)a4,(unsigned int)a5);
		CASE_SYSCALL (getsockopt, (int)a1,(int)a2,(int)a3,(void*)a4,(void*)a5);
		CASE_SYSCALL (fork, );
		CASE_SYSCALL (execve, (char*)a1,(void*)a2,(void*)a3);
		CASE_SYSCALL (exit, (int)a1);
		CASE_SYSCALL (wait4, (int)a1,(int*)a2,(int)a3,(void*)a4);
		CASE_SYSCALL (kill, (int)a1,(int)a2);
		CASE_SYSCALL (uname, (void*)a1);
		CASE_SYSCALL (fcntl, (int)a1,(int)a2,(unsigned long)a3);
		CASE_SYSCALL (flock, (int)a1,(int)a2);
		CASE_SYSCALL (fsync, (int)a1);
		CASE_SYSCALL (fdatasync, (int)a1);
		CASE_SYSCALL (ftruncate, (int)a1,(long long)a2);
		CASE_SYSCALL (getcwd, (char*)a1,(unsigned int)a2);
		CASE_SYSCALL (chdir, (char*)a1);
		CASE_SYSCALL (fchdir, (int)a1);
		CASE_SYSCALL (rename, (char*)a1,(char*)a2);
		CASE_SYSCALL (mkdir, (char*)a1,(int)a2);
		CASE_SYSCALL (rmdir, (char*)a1);
		CASE_SYSCALL (link, (char*)a1,(char*)a2);
		CASE_SYSCALL (unlink, (char*)a1);
		CASE_SYSCALL (symlink, (char*)a1,(char*)a2);
		CASE_SYSCALL (readlink, (char*)a1,(char*)a2,(unsigned int)a3);
		CASE_SYSCALL (chmod, (char*)a1,(int)a2);
		CASE_SYSCALL (fchmod, (int)a1,(int)a2);
		CASE_SYSCALL (chown, (char*)a1,(int)a2,(int)a3);
		CASE_SYSCALL (fchown, (int)a1,(int)a2,(int)a3);
		CASE_SYSCALL (umask, (int)a1);
		CASE_SYSCALL (gettimeofday, (void*)a1,(void*)a2);
		CASE_SYSCALL (getrlimit, (int)a1,(void*)a2);
		CASE_SYSCALL (getrusage, (int)a1,(void*)a2);
		CASE_SYSCALL (sysinfo, (void*)a1);
		CASE_SYSCALL (getuid, );
		CASE_SYSCALL (getgid, );
		CASE_SYSCALL (setuid, (int)a1);
		CASE_SYSCALL (setgid, (int)a1);
		CASE_SYSCALL (geteuid, );
		CASE_SYSCALL (getegid, );
		CASE_SYSCALL (setpgid, (int)a1,(int)a2);
		CASE_SYSCALL (getppid, );
		CASE_SYSCALL (setsid, );
		CASE_SYSCALL (setreuid, (int)a1,(int)a2);
		CASE_SYSCALL (setregid, (int)a1,(int)a2);
		CASE_SYSCALL (getgroups, (unsigned int)a1,(void*)a2);
		CASE_SYSCALL (setgroups, (unsigned int)a1,(void*)a2);
		CASE_SYSCALL (setresuid, (int)a1,(int)a2,(int)a3);
		CASE_SYSCALL (setresgid, (int)a1,(int)a2,(int)a3);
		CASE_SYSCALL (getpgid, (int)a1);
		CASE_SYSCALL (getsid, (int)a1);
		CASE_SYSCALL (rt_sigpending, (void*)a1,(unsigned int)a2);
		CASE_SYSCALL (rt_sigsuspend, (void*)a1,(unsigned int)a2);
		CASE_SYSCALL (sigaltstack, (void*)a1,(void*)a2);
		CASE_SYSCALL (statfs, (char*)a1,(void*)a2);
		CASE_SYSCALL (fstatfs, (int)a1,(void*)a2);
		CASE_SYSCALL (prctl, (int)a1,(unsigned long)a2,(unsigned long)a3,(unsigned long)a4,(unsigned long)a5);
		CASE_SYSCALL (setrlimit, (int)a1,(void*)a2);
		CASE_SYSCALL (chroot, (char*)a1);
		CASE_SYSCALL (gettid, );
		CASE_SYSCALL (tkill, (int)a1,(int)a2);
		CASE_SYSCALL (futex, (int*)a1,(int)a2,(int)a3,(void*)a4,(int*)a5,(int)a6);
		CASE_SYSCALL (sched_getaffinity, (int)a1,(unsigned int)a2,(void*)a3);
		CASE_SYSCALL (getdents64, (int)a1,(void*)a2,(int)a3);
		CASE_SYSCALL (set_tid_address, (int*)a1);
		CASE_SYSCALL (fadvise, (int)a1,(long long)a2,(long long)a3,(int)a4);
		CASE_SYSCALL (clock_gettime, (int)a1,(void*)a2);
		CASE_SYSCALL (clock_getres, (int)a1,(void*)a2);
		CASE_SYSCALL (clock_nanosleep, (int)a1,(int)a2,(void*)a3,(void*)a4);
		CASE_SYSCALL (exit_group, (int)a1);
		CASE_SYSCALL (epoll_ctl, (int)a1,(int)a2,(int)a3,(void*)a4);
		CASE_SYSCALL (openat, (int)a1,(char*)a2,(int)a3,(int)a4);
		CASE_SYSCALL (mkdirat, (int)a1,(char*)a2,(int)a3);
		CASE_SYSCALL (fchownat, (int)a1,(char*)a2,(int)a3,(int)a4,(int)a5);
		CASE_SYSCALL (newfstatat, (int)a1,(char*)a2,(void*)a3,(int)a4);
		CASE_SYSCALL (unlinkat, (int)a1,(char*)a2,(int)a3);
		CASE_SYSCALL (linkat, (int)a1,(char*)a2,(int)a3,(char*)a4,(int)a5);
		CASE_SYSCALL (symlinkat, (char*)a1,(int)a2,(char*)a3);
		CASE_SYSCALL (readlinkat, (int)a1,(char*)a2,(char*)a3,(unsigned int)a4);
		CASE_SYSCALL (fchmodat, (int)a1,(char*)a2,(int)a3,(int)a4);
		CASE_SYSCALL (faccessat, (int)a1,(char*)a2,(int)a3,(int)a4);
		CASE_SYSCALL (pselect6, (int)a1,(void*)a2,(void*)a3,(void*)a4,(void*)a5,(void*)a6);
		CASE_SYSCALL (ppoll, (void*)a1,(unsigned long long)a2,(void*)a3,(void*)a4,(unsigned int)a5);
		CASE_SYSCALL (utimensat, (int)a1,(char*)a2,(void*)a3,(int)a4);
		CASE_SYSCALL (epoll_pwait, (int)a1,(void*)a2,(int)a3,(int)a4,(void*)a5,(unsigned int)a6);
		CASE_SYSCALL (eventfd, (int)a1);
		CASE_SYSCALL (accept4, (int)a1,(void*)a2,(void*)a3,(int)a4);
		CASE_SYSCALL (eventfd2, (int)a1,(int)a2);
		CASE_SYSCALL (epoll_create1, (int)a1);
		CASE_SYSCALL (dup3, (int)a1,(int)a2,(int)a3);
		CASE_SYSCALL (pipe2, (int*)a1,(int)a2);
		CASE_SYSCALL (prlimit64, (int)a1,(int)a2,(void*)a3,(void*)a4);
		CASE_SYSCALL (renameat2, (int)a1,(char*)a2,(int)a3,(char*)a4,(int)a5);
		CASE_SYSCALL (getrandom, (void*)a1,(unsigned int)a2,(int)a3);
		CASE_SYSCALL (statx, (int)a1,(char*)a2,(int)a3,(unsigned int)a4,(void*)a5);
		CASE_SYSCALL (faccessat2, (int)a1,(char*)a2,(int)a3,(int)a4);
    default: {
      printf("Invalid syscall var call -- NR %d\n",  n);
      return -ENOSYS;
    }
  }
}

#endif
